# Generated by Django 3.2.3 on 2021-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
                ('id_number', models.CharField(max_length=11, unique=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
